export type Card = {
  id: string;
};

export const cards: Card[] = [
  { id: 'Ad' },
  { id: '2d' },
  { id: '3d' },
  { id: '4d' },
  { id: '5d' },
  { id: '6d' },
  { id: '7d' },
  { id: '8d' },
  { id: '9d' },
  { id: 'Td' },
  { id: 'Jd' },
  { id: 'Qd' },
  { id: 'Kd' },
  { id: 'Ah' },
  { id: '2h' },
  { id: '3h' },
  { id: '4h' },
  { id: '5h' },
  { id: '6h' },
  { id: '7h' },
  { id: '8h' },
  { id: '9h' },
  { id: 'Th' },
  { id: 'Jh' },
  { id: 'Qh' },
  { id: 'Kh' },
  { id: 'Ac' },
  { id: '2c' },
  { id: '3c' },
  { id: '4c' },
  { id: '5c' },
  { id: '6c' },
  { id: '7c' },
  { id: '8c' },
  { id: '9c' },
  { id: 'Tc' },
  { id: 'Jc' },
  { id: 'Qc' },
  { id: 'Kc' },
  { id: 'As' },
  { id: '2s' },
  { id: '3s' },
  { id: '4s' },
  { id: '5s' },
  { id: '6s' },
  { id: '7s' },
  { id: '8s' },
  { id: '9s' },
  { id: 'Ts' },
  { id: 'Js' },
  { id: 'Qs' },
  { id: 'Ks' },
];
