name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install package dependencies
        run: npm install
        
      - name: Create test build
        run: npm run build
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1


