name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v3
        
      - name: Install package dependencies
        run: npm install
        
      - name: Create test build
        run: npm run build
        
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
          
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          path: ./dist
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
