name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install package dependencies
        run: npm install
        
      - name: Create test build
        run: npm run build
        
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with: 
          path: ./dist

